/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#111417",
        "surface-dim": "#111417",
        "surface-bright": "#37393d",
        "surface-container-lowest": "#0c0e12",
        "surface-container-low": "#191c1f",
        "surface-container": "#1d2023",
        "surface-container-high": "#282a2e",
        "surface-container-highest": "#323539",
        "on-surface": "#e1e2e7",
        "on-surface-variant": "#cbc3d7",
        "inverse-surface": "#e1e2e7",
        "inverse-on-surface": "#2e3134",
        "outline": "#958ea0",
        "outline-variant": "#494454",
        "surface-tint": "#d0bcff",
        "primary": "#d0bcff",
        "on-primary": "#3c0091",
        "primary-container": "#a078ff",
        "on-primary-container": "#340080",
        "inverse-primary": "#6d3bd7",
        "secondary": "#4cd7f6",
        "on-secondary": "#003640",
        "secondary-container": "#03b5d3",
        "on-secondary-container": "#00424e",
        "tertiary": "#d0bcff",
        "on-tertiary": "#37265e",
        "tertiary-container": "#9987c6",
        "on-tertiary-container": "#301f57",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#d0bcff",
        "on-primary-fixed": "#23005c",
        "on-primary-fixed-variant": "#5516be",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5c",
        "tertiary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed": "#210f48",
        "on-tertiary-fixed-variant": "#4d3d76",
        "background": "#111417",
        "on-background": "#e1e2e7",
        "surface-variant": "#323539",
        "void-black": "#000000",
        "surface-deep": "#05070A",
        "electric-violet": "#8B5CF6",
        "cyber-cyan": "#06B6D4",
        "glass-stroke": "rgba(255, 255, 255, 0.1)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "32px",
        "margin-desktop": "64px",
        "container-max": "1600px",
        "section-gap": "80px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-xl": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "label-code": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-xl": ["80px", { lineHeight: "1.0", letterSpacing: "-0.05em", fontWeight: "700" }],
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "label-code": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "spin-slow": "spin 20s linear infinite",
        "spin-reverse": "spin-reverse 25s linear infinite",
        "float": "float 6s ease-in-out infinite",
        "shimmer": "shimmer 2.5s linear infinite",
        "scan": "scan 3s infinite linear",
      },
      keyframes: {
        "spin-reverse": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(-360deg)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        scan: {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100vh)" },
        }
      }
    },
  },
  plugins: [],
}
